# Create an environment named 'ember-build' with these packages by running:
#
#     mamba env create -n ember-build -f environment.yaml
#
# or update an existing, activated environment by running:
#
#     mamba env update -f environment.yaml

channels:
- conda-forge
dependencies:
- cantera=3.0.0
- libcantera-devel=3.0.0
- python=3.11
- scons=4.5.2
- boost-cpp>=1.70
- sundials=6.6.*
- fmt
- tbb
- tbb-devel
- eigen=3.4.0
- cython=3.0.0
- numpy=1.25.*
- pip
- wheel
- packaging
- setuptools>= 75.3.1
- pytest
- h5py=3.9.*  # optional; used by some examples
- matplotlib  # optional; used by some examples
# see doc-environment.yaml for packages needed to build the documentation